import {test,expect} from '@playwright/test';
test('assessment quiz validates answers, saves feedback and opens targeted practice',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Explore all 36 skill guides',exact:true}).click();
 await page.getByRole('button',{name:'Assessments',exact:true}).click();
 await expect(page.locator('.assessment-grid article')).toHaveCount(12);
 await page.screenshot({path:'docs/screenshots/assessments-catalog.png',fullPage:true});
 await page.getByRole('textbox',{name:'Find a skill'}).fill('Python');
 await page.getByRole('button',{name:'Start assessment'}).click();
 await expect(page.getByRole('button',{name:'Next question'})).toBeDisabled();
 await page.getByRole('radio',{name:'30',exact:true}).check();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('radio',{name:'10',exact:true}).check();
 await page.getByRole('button',{name:'Previous',exact:true}).click();
 await expect(page.getByRole('radio',{name:'30',exact:true})).toBeChecked();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('radio',{name:'x == 5',exact:true}).check();
 await page.getByRole('button',{name:'Next question'}).click();
 await expect(page.getByRole('button',{name:'Finish assessment'})).toBeDisabled();
 await page.getByRole('radio',{name:'Ends the function call and provides its result',exact:true}).check();
 await page.getByRole('button',{name:'Finish assessment'}).click();
 await expect(page.locator('.assessment-result')).toContainText('75');
 await expect(page.locator('.assessment-roadmap')).toContainText('Lists');
 await expect(page.getByText('Profile skill score: 0 → 45.',{exact:false})).toBeVisible();
 await page.screenshot({path:'docs/screenshots/assessment-result.png',fullPage:true});
 await page.getByRole('button',{name:'Open my practice guide'}).click();
 await expect(page.locator('.course-detail')).toContainText('Python programming');
 await page.getByRole('button',{name:'Check my foundations'}).click();
 await page.getByRole('button',{name:'View result',exact:true}).click();
 await expect(page.locator('.assessment-result')).toContainText('75');
 await page.reload();await page.getByRole('button',{name:'Assessments',exact:true}).click();
 await page.getByRole('textbox',{name:'Find a skill'}).fill('Python');await page.getByRole('button',{name:'View result',exact:true}).click();await expect(page.locator('.assessment-result')).toContainText('75');
});
test('assessment is usable on mobile with one question at a time',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await page.getByRole('button',{name:'Explore all 36 skill guides',exact:true}).click();
 await page.getByRole('button',{name:'Toggle navigation'}).click();await page.getByRole('button',{name:'Assessments',exact:true}).click();
 await page.getByRole('textbox',{name:'Find a skill'}).fill('public speaking');await page.getByRole('button',{name:'Start assessment'}).click();
 await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
 await page.getByRole('radio').nth(1).check();
 await expect(page.getByRole('button',{name:'Next question'})).toBeEnabled();
 await page.screenshot({path:'docs/screenshots/assessment-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});

test('direct test link preserves the current question and answers after refresh',async({page})=>{
 await page.request.post('/api/auth/demo');
 await page.goto('/assessments');
 await expect(page.getByRole('heading',{name:'Skill assessments',exact:true})).toBeVisible();
 await page.getByRole('textbox',{name:'Find a skill'}).fill('Python');
 await page.getByRole('button',{name:'Start assessment'}).click();
 await page.getByRole('radio',{name:'3',exact:true}).check();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('radio',{name:'10',exact:true}).check();
 await page.reload();
 await expect(page).toHaveURL(/\/assessments$/);
 await expect(page.getByRole('radio',{name:'10',exact:true})).toBeChecked();
 await page.getByRole('button',{name:'Previous',exact:true}).click();
 await expect(page.getByRole('radio',{name:'3',exact:true})).toBeChecked();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('radio',{name:'x == 5',exact:true}).check();
 await page.getByRole('button',{name:'Next question'}).click();
 await page.getByRole('radio',{name:'Ends the function call and provides its result',exact:true}).check();
 await page.getByRole('button',{name:'Finish assessment'}).click();
 await expect(page.locator('.assessment-result')).toContainText('100');
 await page.reload();
 await expect(page.getByRole('heading',{name:'Check your foundations'})).toBeVisible();
});
